name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    steps:
      - name: Start database server
        run: sudo /etc/init.d/mysql start

      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v1 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}

      - name: php --version
        run: php --version

      - name: composer --version
        run: composer --version

      - name: (COMPOSER) Validate composer.json
        run: composer validate

      - name: (COMPOSER) Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --working-dir=.Build/

      - name: (PHP) Lint
        run: .Build/bin/phplint --configuration=.Build/.phplint.yml --no-cache

      - name: (PHPUnit) Run unit tests
        run: php .Build/bin/phpunit --colors --coverage-php=.Build/coverage/unit.cov --configuration .Build/UnitTests.xml;

      - name: (PHPUnit) Run functional tests
        env:
          typo3DatabaseHost: 127.0.0.1
          typo3DatabaseName: typo3
          typo3DatabaseUsername: root
          typo3DatabasePassword: root
          PROCESSOR: ImageMagick
          PROCESSOR_PATH: /usr/bin/
          PROCESSOR_PATH_LZW: /usr/bin/
        run: php .Build/bin/phpunit --process-isolation --colors --coverage-php=.Build/coverage/functional.cov --configuration .Build/FunctionalTests.xml;

      - name: (PHPCov) Merge coverage files
        run: php .Build/bin/phpcov merge .Build/coverage --clover .Build/build/logs/clover.xml

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: .Build/build/logs/clover.xml
